// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;

static class Constants{
	public const string INF_JAVA_CLASS = "com.infantium.unityplugin.InfantiumPlugin";
}

public class InfantiumPlugin{

	AndroidJavaObject infPlugin;
	AndroidJavaObject infantiumSDK;
	public string api_user;
	public string api_key;
	public int device_width;
	public int device_height;

	public InfantiumPlugin(string api_user, string api_key, int device_width = -1, int device_height = -1){
		AndroidJNI.AttachCurrentThread();
		infPlugin = new AndroidJavaObject(Constants.INF_JAVA_CLASS);

		this.api_user = api_user;
		this.api_key = api_key;
		this.device_width = device_width;
		this.device_height = device_height;
	}

	public void initInfantium(){
		infantiumSDK = infPlugin.Call<AndroidJavaObject>("initInfantium", this.api_user, this.api_key, this.device_width, this.device_height);
	}

	public InfantiumResponse callInfantium(string methodName, params object[] args){
		try{
			string response = infantiumSDK.Call<String>(methodName, args);
			return (InfantiumResponse)Enum.Parse(typeof(InfantiumResponse), response);
		}catch (Exception ex){
				Debug.LogError(string.Format("Infantium Unity SDK exception={0}", ex));
		}
	}
	public InfantiumResponse callPlugin(string methodName, params object[] args){
		try{
			AndroidJavaObject response = infPlugin.Call<String>(methodName, args);
			return (InfantiumResponse)Enum.Parse(typeof(InfantiumResponse), response);
		}catch (Exception ex){
			Debug.LogError(string.Format("Infantium Unity Plugin exception={0}", ex));
		}
	}


	/********************
	   INFANTIUM CALLS
	 ********************/

	public InfantiumResponse setContentAppUUID(string contentappUUID){ 
		return this.callInfantium("setContentAppUUID", contentappUUID); 
	}

	public InfantiumResponse setSubContentUUID(string subcontentUUID){ 
		return this.callInfantium("setSubContentUUID", subcontentUUID); 
	}


	/***********************
	   INFANTIUM ELEMENTS
	 ***********************/

	public InfantiumResponse addElement(string element_id, int width, int height, string movement){
		return this.callPlugin("addElement", element_id, width, height, movement); 
	}
	
	public InfantiumResponse addTextElement(string element_id, int width, int height, string movement, string text, string lang){ 
		return this.callPlugin("addTextElement", element_id, width, height, movement, text, lang); 
	}

	public InfantiumResponse addShapeElement(string element_id, int width, int height, string movement, int n_sides){ 
		return this.callPlugin("addShapeElement", element_id, width, height, movement, n_sides); 
	}

	public InfantiumResponse addPaintedElement(string element_id, int width, int height){ 
		return this.callPlugin("addPaintedElement", element_id, width, height); 
	}

	public InfantiumResponse addPictureElement(string element_id, int width, int height){ 
		return this.callPlugin("addPictureElement", element_id, width, height); 
	}

	/***********************
	   INFANTIUM GOALS
	 ***********************/

	public InfantiumResponse addGoal(string goal_id, long time_limit, bool auto_eval, string instructions){ 
		return this.callPlugin("addGoal", goal_id, time_limit, auto_eval, instructions); 
	}

	public InfantiumResponse addSelectionGoal(string goal_id, long time_limit, bool auto_eval, string instructions, int n_correct_choices, int n_incorrect_choices, bool unique_solutions, string needed_action){ 
		return this.callPlugin("addSelectionGoal", goal_id, time_limit, auto_eval, instructions, n_correct_choices, n_incorrect_choices, unique_solutions,needed_action); 
	}

	public InfantiumResponse addMatchingGoal(string goal_id, long time_limit, bool auto_eval, string instructions, string matching_element, string correspondence_type){ 
		return this.callPlugin("addMatchingGoal", goal_id, time_limit, auto_eval, instructions, matching_element, correspondence_type); 
	}

	public InfantiumResponse addTappingGoal(string goal_id, long time_limit, bool auto_eval, string instructions, string element_to_tap){ 
		return this.callPlugin("addTappingGoal", goal_id, time_limit, auto_eval, instructions, element_to_tap); 
	}
	
	public InfantiumResponse newBasicInteraction(string interaction_t, string object_type, string goal_type, int lifetime, int n_concurrent_oks, int n_concurrent_kos){ 
		return this.callPlugin("newBasicInteraction", interaction_t, object_type, goal_type, lifetime, n_concurrent_oks, n_concurrent_kos); 
	}

	/***********************
	   INFANTIUM GAMEPLAY
	 ***********************/

	public InfantiumResponse createGameplay(string subContentUUID){ 
		return this.callInfantium("createGameplay", subContentUUID); 
	}

	public InfantiumResponse startPlaying(){ 
		return this.callInfantium("startPlaying"); 
	}

	public InfantiumResponse closeGameplay(){ 
		return this.callInfantium("closeGameplay"); 
	}

	/***********************
	   INFANTIUM RAWDATA
	 ***********************/

	public InfantiumResponse sendGameRawdata(){ 
		return this.callInfantium("sendGameRawdata"); 
	}
	public InfantiumResponse sendEbookRawdata(){ 
		return this.callInfantium("sendEbookRawdata"); 
	}

	/***************************
	   INFANTIUM APP BEHAVIOURS
	 ***************************/

	public InfantiumResponse returnToInfantiumApp(){
		AndroidJavaClass jc = new AndroidJavaClass("com.unity3d.player.UnityPlayer"); 
		AndroidJavaObject context = jc.GetStatic<AndroidJavaObject>("currentActivity");
		return this.callInfantium("returnToInfantiumApp", context); 
	}

	public InfantiumResponse onPauseInfantium(){
		return this.callInfantium("onPauseInfantium"); 
	}

	public InfantiumResponse onResumeInfantium(){ 
		return this.callInfantium("onResumeInfantium"); 
	}

}

