// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

static class Constants{
	public const string INF_JAVA_CLASS = "com.infantium.unityplugin.InfantiumPlugin";
}

public class InfantiumBypass{

	AndroidJavaObject infPlugin;
	public string api_user;
	public string api_key;
	public int device_width;
	public int device_height;

	public InfantiumBypass(string api_user, string api_key, int device_width = -1, int device_height = -1){
		AndroidJNI.AttachCurrentThread();
		infPlugin = new AndroidJavaObject(Constants.INF_JAVA_CLASS);

		this.api_user = api_user;
		this.api_key = api_key;
		this.device_width = device_width;
		this.device_height = device_height;
	}

	public string initInfantium(){

		string response = infPlugin.Call<string>("initInfantium", this.api_user, this.api_key, this.device_width, this.device_height);
		return response;
	}
}

